version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: spring-app-dev
    working_dir: /app
    command: ["./gradlew", "bootRun"]
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle

  db:
    image: mariadb:latest
    container_name: mariadb-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: